-- MySQL Script generated by MySQL Workbench

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Database mydb2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Database mydb2
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `mydb2` DEFAULT CHARACTER SET utf8 ;
USE `mydb2` ;

-- -----------------------------------------------------
-- Table `mydb2`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb2`.`departamento` ;

CREATE TABLE IF NOT EXISTS `mydb2`.`departamento` (
  `id` INT(1) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb2`.`clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb2`.`clase` ;

CREATE TABLE IF NOT EXISTS `mydb2`.`clase` (
  `id` INT(2) NOT NULL,
  `clase` VARCHAR(45) NOT NULL,
  `departamento` INT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `cls_departamento_fk`
    FOREIGN KEY (`departamento`)
    REFERENCES `mydb2`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `cls_departamento_fk_idx` ON `mydb2`.`clase` (`departamento` ASC) ;


-- -----------------------------------------------------
-- Table `mydb2`.`familia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb2`.`familia` ;

CREATE TABLE IF NOT EXISTS `mydb2`.`familia` (
  `id` INT(3) NOT NULL,
  `familia` VARCHAR(45) NOT NULL,
  `clase` INT(2) NOT NULL,
  `departamento` INT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fam_clase_fk`
    FOREIGN KEY (`clase`)
    REFERENCES `mydb2`.`clase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
ENGINE = InnoDB;

CREATE INDEX `fam_clase_fk_idx` ON `mydb2`.`familia` (`clase` ASC) ;


-- -----------------------------------------------------
-- Table `mydb2`.`articulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb2`.`articulo` ;

CREATE TABLE IF NOT EXISTS `mydb2`.`articulo` (
  `sku` VARCHAR(6) NOT NULL,
  `articulo` VARCHAR(15) NOT NULL,
  `marca` VARCHAR(15) NOT NULL,
  `modelo` VARCHAR(20) NOT NULL,
  `stock` INT(9) NOT NULL,
  `cantidad` INT(9) NOT NULL,
  `descontinuado` TINYINT(4) NOT NULL DEFAULT 0,
  `fechaAlta` DATE NOT NULL DEFAULT CURRENT_DATE,
  `fechaBaja` DATE NOT NULL DEFAULT '1900-01-01',
  `departamento` INT(1) NOT NULL,
  `clase` INT(2) NOT NULL,
  `familia` INT(3) NOT NULL,
  PRIMARY KEY (`sku`),
  CONSTRAINT `dep_fk`
    FOREIGN KEY (`departamento`)
    REFERENCES `mydb2`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cls_fk`
    FOREIGN KEY (`clase`)
    REFERENCES `mydb2`.`clase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fam_fk`
    FOREIGN KEY (`familia`)
    REFERENCES `mydb2`.`familia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `dep_fk_idx` ON `mydb2`.`articulo` (`departamento` ASC);

CREATE INDEX `cls_fk_idx` ON `mydb2`.`articulo` (`clase` ASC);

CREATE INDEX `fam_fk_idx` ON `mydb2`.`articulo` (`familia` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
